### PR TITLE
Use consistent whitespace

### PR DESCRIPTION
**Pull request by Daniel-Trevitz**
Use tabs in cmake to match c file formatting

Signed-off-by: Daniel Trevitz <daniel.trevitz@wika.com>

### CODE REVIEW

**Comment by Daniel-Trevitz** [comment]
Not sure if you're interested in white space fixes; if not just say so.

**Comment by marckleinebudde** [comment]
LGTM!

**Comment by fenugrec** [comment]
> Not sure if you're interested in white space fixes; if not just say so.

Sure, but if you plan on taking on the entire codebase it would have to be done with some kind of script - either clang-format, uncrustify, astyle, etc. Otherwise it's just a losing battle. Here just for the CMakelists it's fine to do manually, since it's not C

**Comment by Daniel-Trevitz** [comment]
> Sure, but if you plan on taking on the entire codebase it would have to be done with some kind of deterministic script - either clang-format, uncrustify, astyle, etc... Otherwise it's just a losing battle. Here just for the CMakelists it's fine to do manually, since it's not C

Absolutely.

I'm pretty sure there is only one good time to fix whitespace ... before it is written.
Main issue I see is that by making any large whitespace change to the project could create much larger diffs for all of the forks out there (including my own!).

I can look into what it will take to add a code formatter; I think it would be pointless if we don't enforce it with git or github.

Is this something we even want though?

**Comment by fenugrec** [comment]
> Is this something we even want though?

Now and then it will annoy someone - you, sometimes me when I look closely; a while back @rickyelopez was maybe going to start on something : https://github.com/candle-usb/candleLight_fw/pull/80#issuecomment-1006809838

> I think it would be pointless if we don't enforce it with git or github.

Dunno, never used hooks for this. It could perhaps be integrated in the CI checks for each PR ? that would force  the contributor to format their stuff properly at an early stage.

>  all of the forks out there

TBH I never really considered the forks at all - I always hope this repo stays good enough (and generic enough) so that the only forks to appear would be small forks that add, say, a weird uncommon board, or some other minor change that doesn't warrant a PR.

**Comment by fenugrec** [comment]
> It gives me something new to learn, I'll see how much of a PIA it is to do this.

Perhaps this
https://github.com/coleaeason/actions-uncrustify 
could be a starting point. First step would be to at least come up with a sane uncrustify.cfg that minimally changes the codebase - at least with that we can tell contributors how to format their stuff.

**Comment by fenugrec** [comment]
PS - moving the conversation to another ticket

**Pull request merged**
