### PR TITLE
fix CMakeLists + explicit LED polarity settings

### PR DESCRIPTION
**Pull request by fenugrec**
I failed to test the build on the last PR merge and broke cmake due to a syntax error (missing ").

Also inverts the LED logic for the canalyze board, and sets explicitly the polarity for all board types.

@brandonros , please test your device against this

### CODE REVIEW

**Comment by brandonros** [comment]
@fenugrec I will test, but can you advise here? https://github.com/candle-usb/candleLight_fw/issues/32#issuecomment-552128547

Looking for a fix so that I do not need to manually override `objcopy` binary path.

**Comment by brandonros** [comment]
@fenugrec we kind of flipped what is happening. now, when device is plugged in: LEDs are off. then, I call resetDevice / setupDevice (I wrote WebUSB interface for this, by the way) and both green + red LED stay solid.

**Comment by brandonros** [comment]
Eh, this is probably good enough. Green stays steady when the device is up, and red blinks on transmission. I say send it through.

**Comment by fenugrec** [comment]
webUSB... 
Yes, I agree the LED behavior is a bit strange but I don't think it's specific to your device. I have another patch to address this. In any case the logic should be correct now  for  all boards.

**Pull request closed without merging**
