### PR TITLE
Uncrustify the code

### PR DESCRIPTION
**Pull request by Daniel-Trevitz**
Add an uncrustify config file and apply the changes it creates.

### CODE REVIEW

**Comment by Daniel-Trevitz** [comment]
The config has most of the rules off, only enabling the rules that seem to be most obvious.

**Comment by marckleinebudde** [comment]
<del>Let the bike shedding begin!</del>

What abou using the Linux kernel coding style?

https://github.com/uncrustify/uncrustify/blob/master/etc/linux.cfg

**Comment by fenugrec** [comment]
> ~Let the bike shedding begin!~
> What abou using the Linux kernel coding style?

Because 1TBS is the True Way !

But more seriously, I'm hoping for just a minimal .cfg that takes care of the worst whitespace offences while changing as little as possible - I believe this commit manages fairly well, but will look closer when I have more time.

**Comment by fenugrec** [comment]
Thanks ! 
I've no problem adjusting the .cfg file as we find new inconsistencies. At least we have a starting point now

**Pull request merged**
