### PR TITLE
feat: add convertdevice xCANFD config info

### PR DESCRIPTION
**Pull request by ConvertDevice**

### CODE REVIEW

**Comment by marckleinebudde** [comment]
Looks good to me!

**Comment by marckleinebudde** [comment]
@ConvertDevice can you rebase, then @fenugrec can merge this

**Comment by fenugrec** [comment]
you just merged master back into your tree... that is not a rebase, and only makes things more complicated for me.

next time,
- always work on a branch, not master
- don't merge back and forth between upstream and your stuff

**Comment by fenugrec** [comment]
rebased and merged in 4dc288d1744166e66ed72e95257524846d9b2b02

**Pull request closed without merging**
