### PR TITLE
ci: add convertdevice-xcan01 hardware support

### PR DESCRIPTION
**Pull request by ConvertDevice**
add convertdevice-xcan01 hardware support

### CODE REVIEW

**Review by ConvertDevice — COMMENTED** [review]
reviewed

**Review by ConvertDevice — COMMENTED** [review]
code reviewed

**Comment by marckleinebudde** [comment]
Please run `uncrustify` and squash the changes
`uncrustify -c ./uncrustify.cfg --replace $(find include src -name "*.[ch]")`

**Comment by marckleinebudde** [comment]
This is a step in the right direction, please only include changes related to adding you board, ignore the other changes.

**Comment by marckleinebudde** [comment]
Looks good, please make it one patch only.

**Comment by ConvertDevice** [comment]
What's next?

**Comment by fenugrec** [comment]
> What's next?

thanks for adapting your PR. Next, you wait for me to have a bit of time to merge it.

**Comment by fenugrec** [comment]
merged via e0e04ea9387ff0ec1d770a04fd5f2306f4161d10

**Pull request closed without merging**
