### PR TITLE
RFC : completely remove flash-as-eeprom emulation for get/set_USER_ID

### PR DESCRIPTION
**Pull request by fenugrec**
A follow-up to the discussion in https://github.com/candle-usb/candleLight_fw/issues/91 .

Any thoughts ? There's no rush to delete probably-good code, but if it's not used by anyone...

This would remove all the relevant code and adjusts the linker scripts accordingly.

### CODE REVIEW

**Comment by Daniel-Trevitz** [comment]
I've yet to see the value in it. totally unsupported in linux as far as I can tell.

**Comment by fenugrec** [comment]
@HubertD  , any thoughts on this ?

**Comment by marckleinebudde** [comment]
Go ahead, remove that code.

**Comment by fenugrec** [comment]
> The firmware provides proper device unique serial numbers via the USB interface directly.

Yes, I'm just not sure why Hubert went through the trouble of adding a settable user_id ...

Eh, I can always revert the removal if something pops up. But I think it won't be missed.

**Comment by fenugrec** [comment]
Rebase + merged in a0caf93e50edd081db3c6fbc3f36bc720c780a76 .

**Pull request closed without merging**
