### PR TITLE
Document new features: Bus Error Reporting and query device state

### PR DESCRIPTION
**Pull request by marckleinebudde**

### CODE REVIEW

**Comment by fenugrec** [comment]
looks good.
I'm having a hard time following the process between the posts with submitted patches on linux-can mailing list, and eventual merge in linux trunk... unlike a PR here, there isn't an obvious trace of a patchset being accepted/approved , merged by whoever's in charge of linux-can, and then eventual merge into trunk...

**Comment by marckleinebudde** [comment]
In the Linux kernel new CAN features go via the `linux-can-next` tree to the `net-next-tree` and during the merge window into Linus's tree. I'm responsible for the `linux-can-next` tree. Once patches are in `net-next` they will hit mainline. The patches to document these features are `net-next` and will be in the `v6.2` release of Linux.

**Comment by jhofstee** [comment]
And for what it is worth, I have the changes to implement it as well, but that waits for the fixes for the error-reporting to be merged first.

**Comment by fenugrec** [comment]
> but that waits for the fixes for the error-reporting to be merged first.

Do you mean #119 or the kernel changes ?

**Comment by jhofstee** [comment]
I meant https://github.com/candle-usb/candleLight_fw/pull/119 indeed, I wasn't aware it is merged. Sorry for that, but I get thousand of notifications a day, missed it somehow. I will rebase the implementation on top of this.

**Pull request merged**
