### PR TITLE
gs_usb cleanups

### PR DESCRIPTION
**Pull request by marckleinebudde**
First some cleanups, then mark `struct gs_*` as aligned to 4 bytes.

### CODE REVIEW

**Comment by fenugrec** [comment]
- Do we want some kind of more-compiler-portable method of marking aligned data ? Granted we're pretty much tied to gcc right now.

- we're already requiring C11 support, we could use a `Static_assert()` to validate correct struct size at compile-time ?

**Comment by marckleinebudde** [comment]
> Do we want some kind of more-compiler-portable method of marking aligned data?

These macros are defined in the `STM32_HAL` to make it portable.

> Granted we're pretty much tied to gcc right now.

The only other compiler I can think of is `clang`, we can solve the problem, once it hits us :)

> we're already requiring C11 support, we could use a Static_assert() to validate correct struct size at compile-time ?

Yes could be done, but I don't see the benefit.

Now we say the compiler, don't add holes and assume it's aligned to 4 bytes.

If you have neither packed nor aligned, the compiler assumes 4 bytes alignment. This is how I found the issue, I tried to assign a pointer to a packed struct to a pointer of a non packed struct and the compiler warned that the packed pointer doesn't have a 4 byte alignment.

**Comment by marckleinebudde** [comment]
After seeping over it, decided to use `__aligned` as in the Linux kernel and add a minimal `compiler.h`. The `__ALIGN_BEGIN` and `__ALIGN_END` ist just too ugly :)

**Comment by marckleinebudde** [comment]
changes:
* imported and improved `compiler.h` from FreeBSD
* use `__algined()` instead of `__ALIGN_BEGIN` and `__ALIGN_END`

**Comment by fenugrec** [comment]
>     * imported and improved `compiler.h` from FreeBSD

Hm.. Cool, but  I see it includes a "<sys/cdefs.h>" (which may or may not work when compiling from a windows host ?)
I notice ARRAY_SIZE in there, but what else do we need from that file ?

>     * use `__algined()` instead of `__ALIGN_BEGIN` and `__ALIGN_END`

+1

**Comment by marckleinebudde** [comment]
> Hm.. Cool, but I see it includes a "<sys/cdefs.h>" (which may or may not work when compiling from a windows host ?) I notice ARRAY_SIZE in there, but what else do we need from that file ?

Removed `cdefs.h`, don't know if this would fail on Windows :)

The `barrier`, `READ_ONCE` and `WRITE_ONCE` is needed for the Linux lists, so I don't want to remove this and add back later.

+ rebased to latest master.

**Comment by marckleinebudde** [comment]
Feel free to merge.

**Comment by marckleinebudde** [comment]
Dammit, didn't want to closed it...

**Comment by fenugrec** [comment]
thanks !

**Pull request merged**
