### PR TITLE
CANAlyze support

### PR DESCRIPTION
**Pull request by brandonros**

### CODE REVIEW

**Comment by brandonros** [comment]
@kkuchera

**Comment by fenugrec** [comment]
Merged, thanks

**Comment by brandonros** [comment]
the LED activity doesn’t work perfectly

they show up before device is reset/started but then they both turn off

**Comment by fenugrec** [comment]
Didn't you test this device before submitting the PR ? 
Do they blink with TX/RX activity ?

**Comment by brandonros** [comment]
i did test
device works perfectly
just, no blinking of LEDs on activity and no green LED when device is connected/initialized

before device is reset: both green and red steady

Regards,

Brandon

________________________________

**Comment by fenugrec** [comment]
the canalyze has active-high LED signals. And there was a typo in CMakeLists.txt, missing a "

**Comment by fenugrec** [comment]
Please check https://github.com/candle-usb/candleLight_fw/pull/35 for a possible fix

**Pull request merged**
